GET http://eclipse/api/widgets HTTP/1.1


###


POST http://eclipse/api/widgets HTTP/1.1
Content-Type: application/json

{
	"type": "weer",
	"params": "die info"
}

###

PUT http://eclipse/api/widgets/3 HTTP/1.1
Content-Type: application/json

{
	"type": "type updated",
	"params": "params updated"
}

###

DELETE http://eclipse/api/widgets/6

 