GET http://eclipse/api/widgets HTTP/1.1

### 
GET http://eclipse/api/user_settings HTTP/1.1

###
GET http://eclipse/api/mirrors HTTP/1.1

###check if city bestaat 

GET http://eclipse/api/weather?city=emmen HTTP/1.1
### Haal specefieke widgets op basis van de type naam

GET http://eclipse/api/widgets/search?search=weather HTTP/1.1
### alle post's
# maak een nieuwe widget aan 
POST http://eclipse/api/widgets HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: 

{
	"type": "weer",
	"params": "die info"
}
### Maak een gebruiker aan

POST http://eclipse/api/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
	"name": "test",
	"email": "bob@de.bouwer",
	"password": "123456",
	"password_confirmation": "123456",
}

### log de gebruiker in

POST http://eclipse/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
	"email": "bob@de.bouwer",
	"password": "123456",
}

### log een gebruiker uit
POST http://eclipse/api/logout HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization:  


### alle put requests
### update een widget op basis van id

PUT http://eclipse/api/widgets/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization:  

{
	"type": "type updated",
	"params": "params updated"
}

### update user settings

PUT http://eclipse/api/user_settings/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization:  

{
	"type": "type updated",
	"params": "params updated"
}


### update mirror

PUT http://eclipse/api/mirrors/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization:  

{
	"type": "type updated",
	"params": "params updated"
}

### delete routs
### delete een widget

DELETE http://eclipse/api/widgets/5
Accept: application/json
Authorization: 
