GET http://eclipse/api/widgets HTTP/1.1
Accept: application/json
Authorization: Bearer {token}

### 
GET http://eclipse/api/user_settings/search/1 HTTP/1.1
Accept: application/json
Authorization: Bearer {token}

###check if city bestaat 

GET http://eclipse/api/weather?city=emmen HTTP/1.1
Authorization: Bearer {token}

### alle post's
### Maak een gebruiker aan
POST http://eclipse/api/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
	"name": "test",
	"email": "bob@de.bouwer",
	"password": "123456",
	"password_confirmation": "123456"
}

### log de gebruiker in

POST http://eclipse/api/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
	"email": "test@test.test",
	"password": "password"
}

### log een gebruiker uit
POST http://eclipse/api/logout HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}

### maak een nieuwe widget aan

POST http://eclipse/api/widgets/store HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}

{
	"type": "weer",
	"params": "die info",
	"recentdata": "recentdata"
}

### krijg alle user_settings

POST http://eclipse/api/user_settings/update?id=1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}

{
	"type": "weer",
	"params": "die info",
	"recentdata": "recentdata"
}

### alle put requests
### update een widget op basis van id

PUT http://eclipse/api/widgets/update?id=3 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {token}

{
	"type": "type updated",
	"params": "params updated",
	"recentdata": "recentdata"
}

### delete routs
### delete een widget
# no longer available
DELETE http://eclipse/api/widgets/destroy/5
Accept: application/json
Authorization: Bearer {token}
